name: Automated Testing
on:
    push:
        branches: [main, next]
    pull_request:
        branches: [main, next]
    workflow_dispatch:
jobs:
    e2e-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Modules
              run: npm ci
            - name: Run Cypress
              uses: cypress-io/github-action@v2
              with:
                  build: npm run build
                  start: npm run test.e2e.run
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: npm ci
            - name: Run Jest Tests
              run: npm run test.unit
